### ISSUE TITLE
Fix histogram for long inputs

### ISSUE THREAD

**Issue by johnyburd** [johnyburd/3dfeeling#1]
As a user, I want my histogram generator to not randomly break during demos

**Comment by james-a-johnson** [comment]
After debugging this problem I discovered that this bug was caused by a malformed input to object generation and not caused by a bug in the software. If there are too many newlines in a row, then an empty list will be passed to the object generation software which is currently an undefined behavior and this problem should be prevented from occurring elsewhere in the software.
